/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Access Token */
        post: operations["login_access_token_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Device */
        post: operations["register_device_api_v1_devices__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Telemetry Batch
         * @description Idempotent batch upload of telemetry data.
         */
        post: operations["upload_telemetry_batch_api_v1_telemetry_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction Job */
        get: operations["get_prediction_job_api_v1_predictions_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_api_v1_alerts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_v1_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Check */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /** Prediction Id */
            prediction_id?: string | null;
            /** Alert Type */
            alert_type: string;
            severity: components["schemas"]["AlertSeverityEnum"];
            /** Title */
            title: string;
            /** Message */
            message?: string | null;
            status: components["schemas"]["AlertStatusEnum"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
        };
        /**
         * AlertSeverityEnum
         * @enum {string}
         */
        AlertSeverityEnum: "INFO" | "WARNING" | "HIGH" | "CRITICAL";
        /**
         * AlertStatusEnum
         * @enum {string}
         */
        AlertStatusEnum: "OPEN" | "ACKNOWLEDGED" | "RESOLVED" | "DISMISSED";
        /** AnalyticsOverview */
        AnalyticsOverview: {
            /** Total Devices */
            total_devices: number;
            /** Online Devices */
            online_devices: number;
            /** Offline Devices */
            offline_devices: number;
            /** Healthy Devices */
            healthy_devices: number;
            /** Warning Devices */
            warning_devices: number;
            /** Critical Devices */
            critical_devices: number;
            /** Active Alerts */
            active_alerts: number;
            /** Average System Health */
            average_system_health: number;
        };
        /** Body_login_access_token_api_v1_auth_login_post */
        Body_login_access_token_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /** Device Id */
            device_id: string;
            /** Hostname */
            hostname?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model?: string | null;
            /** Operating System */
            operating_system?: string | null;
            /** Os Version */
            os_version?: string | null;
            /** Architecture */
            architecture?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /** Schema Version */
            schema_version?: string | null;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Device Id */
            device_id: string;
            /** Hostname */
            hostname?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model?: string | null;
            /** Operating System */
            operating_system?: string | null;
            /** Os Version */
            os_version?: string | null;
            /** Architecture */
            architecture?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /** Schema Version */
            schema_version?: string | null;
            /** Id */
            id: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Is Online */
            is_online: boolean;
            /** Is Active */
            is_active: boolean;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatusEnum
         * @enum {string}
         */
        JobStatusEnum: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        /** PredictionJobOut */
        PredictionJobOut: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /** Sample Id */
            sample_id: string;
            status: components["schemas"]["JobStatusEnum"];
            /** Error Message */
            error_message?: string | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * RoleEnum
         * @enum {string}
         */
        RoleEnum: "ADMIN" | "ENGINEER" | "OPERATOR" | "VIEWER";
        /** TelemetryBatchIn */
        TelemetryBatchIn: {
            /** Samples */
            samples: components["schemas"]["TelemetryIn"][];
        };
        /** TelemetryBatchResponse */
        TelemetryBatchResponse: {
            /** Accepted */
            accepted: number;
            /** Duplicates */
            duplicates: number;
            /** Invalid */
            invalid: number;
            /** Prediction Triggered */
            prediction_triggered: number;
        };
        /** TelemetryIn */
        TelemetryIn: {
            /** Sample Id */
            sample_id: string;
            /** Device Id */
            device_id: string;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
            /** Sequence Number */
            sequence_number?: number | null;
            /** Schema Version */
            schema_version?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /** Collection Duration Ms */
            collection_duration_ms?: number | null;
            /** Cpu Usage Percent */
            cpu_usage_percent?: number | null;
            /** Cpu Frequency Current Mhz */
            cpu_frequency_current_mhz?: number | null;
            /** Memory Percent */
            memory_percent?: number | null;
            /** Memory Used Bytes */
            memory_used_bytes?: number | null;
            /** Memory Available Bytes */
            memory_available_bytes?: number | null;
            /** Swap Percent */
            swap_percent?: number | null;
            /** Disk Usage Percent */
            disk_usage_percent?: number | null;
            /** Disk Read Bytes Per Sec */
            disk_read_bytes_per_sec?: number | null;
            /** Disk Write Bytes Per Sec */
            disk_write_bytes_per_sec?: number | null;
            /** Disk Busy Percent */
            disk_busy_percent?: number | null;
            /** Disk Latency Ms */
            disk_latency_ms?: number | null;
            /** Network Upload Bytes Per Sec */
            network_upload_bytes_per_sec?: number | null;
            /** Network Download Bytes Per Sec */
            network_download_bytes_per_sec?: number | null;
            /** Battery Percent */
            battery_percent?: number | null;
            /** Battery Plugged */
            battery_plugged?: boolean | null;
            /** Battery Time Left Seconds */
            battery_time_left_seconds?: number | null;
            /** Gpu Usage Percent */
            gpu_usage_percent?: number | null;
            /** Gpu Memory Used Bytes */
            gpu_memory_used_bytes?: number | null;
            /** Gpu Memory Total Bytes */
            gpu_memory_total_bytes?: number | null;
            /** Gpu Temperature C */
            gpu_temperature_c?: number | null;
            /** Cpu Temperature C */
            cpu_temperature_c?: number | null;
            /** Storage Temperature C */
            storage_temperature_c?: number | null;
            /** Process Count */
            process_count?: number | null;
            /** Uptime Seconds */
            uptime_seconds?: number | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
            /** @default VIEWER */
            role: components["schemas"]["RoleEnum"] | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Id */
            id: string;
            role: components["schemas"]["RoleEnum"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_access_token_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_api_v1_devices__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_telemetry_batch_api_v1_telemetry_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_job_api_v1_predictions_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_v1_alerts__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
        };
    };
    get_overview_api_v1_analytics_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
