"""Initial Phase 3 schema

Revision ID: 29b63f277b92
Revises: 
Create Date: 2026-08-22 22:18:16.846863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b63f277b92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ENGINEER', 'OPERATOR', 'VIEWER', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('device_capabilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('available', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'ERROR', 'NOT_APPLICABLE', name='capabilitystatusenum'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('collector_version', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_capabilities_device_id'), 'device_capabilities', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_capabilities_id'), 'device_capabilities', ['id'], unique=False)
    op.create_table('prediction_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatusenum'), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_jobs_device_id'), 'prediction_jobs', ['device_id'], unique=False)
    op.create_index(op.f('ix_prediction_jobs_id'), 'prediction_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_jobs_sample_id'), 'prediction_jobs', ['sample_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('feature_version', sa.String(), nullable=True),
    sa.Column('label_schema_version', sa.String(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('prediction_probability', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('anomaly_label', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('inference_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_device_id'), 'predictions', ['device_id'], unique=False)
    op.create_index('ix_predictions_device_timestamp', 'predictions', ['device_id', 'timestamp_utc'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_sample_id'), 'predictions', ['sample_id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp_utc'), 'predictions', ['timestamp_utc'], unique=False)
    op.create_table('telemetry_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('collection_duration_ms', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('cpu_frequency_current_mhz', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('memory_used_bytes', sa.Float(), nullable=True),
    sa.Column('memory_available_bytes', sa.Float(), nullable=True),
    sa.Column('swap_percent', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('disk_read_bytes_per_sec', sa.Float(), nullable=True),
    sa.Column('disk_write_bytes_per_sec', sa.Float(), nullable=True),
    sa.Column('disk_busy_percent', sa.Float(), nullable=True),
    sa.Column('disk_latency_ms', sa.Float(), nullable=True),
    sa.Column('network_upload_bytes_per_sec', sa.Float(), nullable=True),
    sa.Column('network_download_bytes_per_sec', sa.Float(), nullable=True),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('battery_plugged', sa.Boolean(), nullable=True),
    sa.Column('battery_time_left_seconds', sa.Float(), nullable=True),
    sa.Column('gpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('gpu_memory_used_bytes', sa.Float(), nullable=True),
    sa.Column('gpu_memory_total_bytes', sa.Float(), nullable=True),
    sa.Column('gpu_temperature_c', sa.Float(), nullable=True),
    sa.Column('cpu_temperature_c', sa.Float(), nullable=True),
    sa.Column('storage_temperature_c', sa.Float(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sample_id', name='uq_telemetry_device_sample')
    )
    op.create_index('ix_telemetry_device_timestamp', 'telemetry_samples', ['device_id', 'timestamp_utc'], unique=False)
    op.create_index(op.f('ix_telemetry_samples_device_id'), 'telemetry_samples', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_samples_id'), 'telemetry_samples', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_samples_sample_id'), 'telemetry_samples', ['sample_id'], unique=False)
    op.create_index(op.f('ix_telemetry_samples_timestamp_utc'), 'telemetry_samples', ['timestamp_utc'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('access_role', sa.Enum('OWNER', 'ENGINEER', 'OPERATOR', 'VIEWER', name='accessroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'HIGH', 'CRITICAL', name='alertseverityenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alertstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RECOMMENDED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatusenum'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_device_id'), 'maintenance_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_device_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_telemetry_samples_timestamp_utc'), table_name='telemetry_samples')
    op.drop_index(op.f('ix_telemetry_samples_sample_id'), table_name='telemetry_samples')
    op.drop_index(op.f('ix_telemetry_samples_id'), table_name='telemetry_samples')
    op.drop_index(op.f('ix_telemetry_samples_device_id'), table_name='telemetry_samples')
    op.drop_index('ix_telemetry_device_timestamp', table_name='telemetry_samples')
    op.drop_table('telemetry_samples')
    op.drop_index(op.f('ix_predictions_timestamp_utc'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_sample_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index('ix_predictions_device_timestamp', table_name='predictions')
    op.drop_index(op.f('ix_predictions_device_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_prediction_jobs_sample_id'), table_name='prediction_jobs')
    op.drop_index(op.f('ix_prediction_jobs_id'), table_name='prediction_jobs')
    op.drop_index(op.f('ix_prediction_jobs_device_id'), table_name='prediction_jobs')
    op.drop_table('prediction_jobs')
    op.drop_index(op.f('ix_device_capabilities_id'), table_name='device_capabilities')
    op.drop_index(op.f('ix_device_capabilities_device_id'), table_name='device_capabilities')
    op.drop_table('device_capabilities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
