"""Add top processes

Revision ID: 7b968519fe9b
Revises: e52621a96ac7
Create Date: 2026-08-24 18:24:49.850748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b968519fe9b'
down_revision: Union[str, Sequence[str], None] = 'e52621a96ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_samples', sa.Column('top_processes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_samples', 'top_processes')
    # ### end Alembic commands ###
