"""Add issue model

Revision ID: e52621a96ac7
Revises: 29b63f277b92
Create Date: 2026-08-24 18:05:59.617469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52621a96ac7'
down_revision: Union[str, Sequence[str], None] = '29b63f277b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('condition_band', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'HIGH', 'CRITICAL', name='issueseverityenum'), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'INVESTIGATING', 'ACTION_REQUIRED', 'VERIFYING', 'PERSISTING', 'RESOLVED', 'ESCALATED', 'DISMISSED', name='issuestatusenum'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('verification_metric', sa.String(), nullable=True),
    sa.Column('verification_operator', sa.String(), nullable=True),
    sa.Column('verification_target', sa.Float(), nullable=True),
    sa.Column('verification_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('verification_required_consecutive_samples', sa.Integer(), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), nullable=True),
    sa.Column('last_verification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('likely_causes', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('evidence_level', sa.Enum('CONFIRMED_BY_TELEMETRY', 'SUPPORTED', 'POSSIBLE', 'UNKNOWN', name='evidencelevelenum'), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('prediction_id', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_device_id'), 'issues', ['device_id'], unique=False)
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.add_column('alerts', sa.Column('issue_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_issue_id'), 'alerts', ['issue_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'issues', ['issue_id'], ['id'])
    op.add_column('maintenance_records', sa.Column('issue_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_maintenance_records_issue_id'), 'maintenance_records', ['issue_id'], unique=False)
    op.create_foreign_key(None, 'maintenance_records', 'issues', ['issue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_records_issue_id'), table_name='maintenance_records')
    op.drop_column('maintenance_records', 'issue_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_issue_id'), table_name='alerts')
    op.drop_column('alerts', 'issue_id')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_device_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
